import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "developers"},
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("unsubscribe_token", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "newsletter_subscribers"},
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("status", models.CharField(choices=[("Released", "Released"), ("Upcoming", "Upcoming"), ("In Development", "In Development")], max_length=32)),
                ("platforms", models.JSONField(blank=True, default=list)),
                ("image_path", models.CharField(max_length=500)),
                ("banner_path", models.CharField(blank=True, max_length=500, null=True)),
                ("game_file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("game_link", models.URLField(blank=True, max_length=500, null=True)),
                ("changelog", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wishlist_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("play_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("developer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="games", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "games"},
        ),
        migrations.CreateModel(
            name="DataFolder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="folders", to=settings.AUTH_USER_MODEL)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="api.datafolder")),
            ],
            options={"db_table": "data_folders"},
        ),
        migrations.CreateModel(
            name="DataFolderFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("folder", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="files", to="api.datafolder")),
                ("uploader", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="data_files", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "data_folder_files"},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("max_attendees", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "events"},
        ),
        migrations.CreateModel(
            name="GameFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("os_type", models.CharField(max_length=50)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file_path", models.CharField(max_length=500)),
                ("original_file_size", models.BigIntegerField(blank=True, null=True)),
                ("compressed_file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("is_compressed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="files", to="api.game")),
            ],
            options={"db_table": "game_files"},
        ),
        migrations.CreateModel(
            name="GameOfMonth",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vote_month", models.IntegerField()),
                ("vote_year", models.IntegerField()),
                ("total_votes", models.IntegerField(default=0)),
                ("rank_position", models.IntegerField(default=0)),
                ("is_winner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_rankings", to="api.game")),
            ],
            options={"db_table": "game_of_month"},
        ),
        migrations.CreateModel(
            name="GameStatistic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("statistic_type", models.CharField(choices=[("download", "Download"), ("play", "Play"), ("view", "View")], max_length=20)),
                ("user_ip", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="api.game")),
            ],
            options={"db_table": "game_statistics"},
        ),
        migrations.CreateModel(
            name="GameVote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vote_month", models.IntegerField()),
                ("vote_year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="api.game")),
                ("voter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="game_votes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "game_votes"},
        ),
        migrations.CreateModel(
            name="GameWishlist",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishlist_entries", to="api.game")),
            ],
            options={"db_table": "game_wishlist"},
        ),
        migrations.CreateModel(
            name="SharedAccess",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resource_type", models.CharField(choices=[("folder", "Folder"), ("file", "File")], max_length=16)),
                ("resource_id", models.IntegerField()),
                ("permission_level", models.CharField(choices=[("read", "Read"), ("write", "Write")], default="read", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("granted_by_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares_granted", to=settings.AUTH_USER_MODEL)),
                ("granted_to_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shared_with_me", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "shared_access"},
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("log_level", models.CharField(default="info", max_length=16)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "system_logs"},
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(default="en", max_length=10)),
                ("theme_preference", models.CharField(default="light", max_length=20)),
                ("notification_preferences", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "user_preferences"},
        ),
        migrations.CreateModel(
            name="EventAttendee",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendees", to="api.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_attendance", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_attendees"},
        ),
        migrations.AddIndex(model_name="game", index=models.Index(fields=["developer"], name="games_develop_222994_idx")),
        migrations.AddIndex(model_name="game", index=models.Index(fields=["genre"], name="games_genre_ac3a20_idx")),
        migrations.AddIndex(model_name="game", index=models.Index(fields=["status"], name="games_status_def24c_idx")),
        migrations.AddIndex(model_name="game", index=models.Index(fields=["release_date"], name="games_release_779b0a_idx")),
        migrations.AddIndex(model_name="game", index=models.Index(fields=["created_at"], name="games_created_51ed57_idx")),
        migrations.AddIndex(model_name="gamefile", index=models.Index(fields=["game"], name="game_files_game_id_42f1f8_idx")),
        migrations.AddIndex(model_name="gamefile", index=models.Index(fields=["os_type"], name="game_files_os_type_353322_idx")),
        migrations.AddIndex(model_name="gamefile", index=models.Index(fields=["device_type"], name="game_files_device__a814ce_idx")),
        migrations.AddIndex(model_name="gamewishlist", index=models.Index(fields=["game"], name="game_wishli_game_id_16e2da_idx")),
        migrations.AddConstraint(model_name="gamewishlist", constraint=models.UniqueConstraint(fields=("game", "email"), name="unique_wishlist_entry")),
        migrations.AddIndex(model_name="gamestatistic", index=models.Index(fields=["game"], name="game_statis_game_id_ca79ba_idx")),
        migrations.AddIndex(model_name="gamestatistic", index=models.Index(fields=["statistic_type"], name="game_statis_statist_6fac68_idx")),
        migrations.AddIndex(model_name="datafolder", index=models.Index(fields=["owner"], name="data_folder_owner_i_c3b287_idx")),
        migrations.AddIndex(model_name="datafolder", index=models.Index(fields=["parent"], name="data_folder_parent__5d2f92_idx")),
        migrations.AddIndex(model_name="datafolderfile", index=models.Index(fields=["folder"], name="data_folder_folder__bced1d_idx")),
        migrations.AddIndex(model_name="datafolderfile", index=models.Index(fields=["uploader"], name="data_folder_uploade_15634e_idx")),
        migrations.AddIndex(model_name="gamevote", index=models.Index(fields=["vote_month", "vote_year"], name="game_votes_vote_mo_88a783_idx")),
        migrations.AddIndex(model_name="gamevote", index=models.Index(fields=["game"], name="game_votes_game_id_76a40b_idx")),
        migrations.AddConstraint(model_name="gamevote", constraint=models.UniqueConstraint(fields=("voter", "game", "vote_month", "vote_year"), name="unique_vote_per_user_per_month")),
        migrations.AddIndex(model_name="gameofmonth", index=models.Index(fields=["vote_month", "vote_year"], name="game_of_mon_vote_mo_e72c06_idx")),
        migrations.AddConstraint(model_name="gameofmonth", constraint=models.UniqueConstraint(fields=("game", "vote_month", "vote_year"), name="unique_game_per_month")),
        migrations.AddIndex(model_name="event", index=models.Index(fields=["event_date"], name="events_event_d_ec8074_idx")),
        migrations.AddIndex(model_name="event", index=models.Index(fields=["creator"], name="events_creator_a4cbbe_idx")),
        migrations.AddIndex(model_name="eventattendee", index=models.Index(fields=["event"], name="event_atten_event_i_5a200c_idx")),
        migrations.AddIndex(model_name="eventattendee", index=models.Index(fields=["user"], name="event_atten_user_id_28aef5_idx")),
        migrations.AddConstraint(model_name="eventattendee", constraint=models.UniqueConstraint(fields=("event", "user"), name="unique_event_user")),
    ]
